#!/bin/bash
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Tobias Bäumer — part of Codeenstein 3D (see LICENSE)
#
# Renders the coturn config for this deployment and execs the relay.
#
# Why a config file instead of CLI flags: coturn takes every setting as a
# command-line option, but a process's argv is world-readable on the host
# (`ps` sees into containers), and `static-auth-secret` is the one value that
# must never be exposed that way — it is the key the signaling server signs
# minted credentials with, so leaking it means anyone can mint relay creds.
# The rendered file lives on a tmpfs owned by this container's user.
#
# Why concatenation instead of templating: coturn has no env-var support and
# the image has no `envsubst`, so *something* has to inject the deployment
# values. Appending generated lines to a static, placeholder-free base file
# keeps the security-critical part (turnserver.conf.base's denied-peer-ip
# block) readable exactly as applied, and sidesteps every quoting/escaping
# hazard a sed-substitution template would introduce around the secret.

set -euo pipefail

BASE_CONF="${TURN_BASE_CONF:-/etc/coturn/turnserver.conf.base}"
RENDERED_CONF="${TURN_RENDERED_CONF:-/tmp/turnserver.conf}"
CERT_DIR="${TURN_CERT_DIR:-/etc/coturn/certs}"

die() {
  echo "[coturn-entrypoint] $1" >&2
  exit 1
}

[ -r "$BASE_CONF" ] || die "base config not readable at $BASE_CONF (is the bind mount in place?)"

# Fail fast and specifically: coturn started without these would come up as an
# unauthenticated or wrongly-realmed relay, which is precisely the failure mode
# the whole design is trying to make impossible.
[ -n "${TURN_REALM:-}" ] || die "TURN_REALM is required (e.g. turn.example.org) — see docker/.env.example"
[ -n "${TURN_SECRET:-}" ] || die "TURN_SECRET is required and must match the signaling server's CODEENSTEIN_MULTIPLAYER_TURN_SECRET"

umask 077
: > "$RENDERED_CONF" || die "cannot write $RENDERED_CONF (expected a writable tmpfs)"
cat "$BASE_CONF" > "$RENDERED_CONF"

emit() { printf '%s\n' "$1" >> "$RENDERED_CONF"; }

emit ""
emit "# --- Generated by entrypoint.sh from the environment ---"
emit "realm=${TURN_REALM}"
emit "server-name=${TURN_REALM}"
emit "static-auth-secret=${TURN_SECRET}"

# Quotas: bound what a single leaked credential, or a bad day, can cost.
emit "user-quota=${TURN_USER_QUOTA:-12}"
emit "total-quota=${TURN_TOTAL_QUOTA:-1200}"
if [ -n "${TURN_MAX_BPS:-}" ]; then emit "max-bps=${TURN_MAX_BPS}"; fi

emit "listening-port=${TURN_LISTENING_PORT:-3478}"
emit "min-port=${TURN_MIN_PORT:-49160}"
emit "max-port=${TURN_MAX_PORT:-49200}"

# Bind only where asked. Unset means every interface — fine on a single-homed
# VPS, wrong on a box with an internal NIC you don't want a relay listening on.
if [ -n "${TURN_LISTENING_IP:-}" ]; then
  for ip in ${TURN_LISTENING_IP//,/ }; do emit "listening-ip=${ip}"; done
fi

# `auto` asks the image's own helper to resolve the public IP over DNS. Only
# needed when the host is behind NAT and doesn't hold its public IP directly.
if [ "${TURN_EXTERNAL_IP:-}" = "auto" ]; then
  detected="$(detect-external-ip)" || die "detect-external-ip failed; set TURN_EXTERNAL_IP explicitly"
  [ -n "$detected" ] || die "detect-external-ip returned nothing; set TURN_EXTERNAL_IP explicitly"
  emit "external-ip=${detected}"
elif [ -n "${TURN_EXTERNAL_IP:-}" ]; then
  emit "external-ip=${TURN_EXTERNAL_IP}"
fi

# TLS is what gets through networks that block everything but HTTPS-looking
# traffic. Optional here so a relay can be brought up on plain 3478 first and
# TLS added once certs are mounted, but a half-configured TLS setup (port with
# no cert) is a hard error rather than a silently plaintext-only relay.
if [ -n "${TURN_TLS_PORT:-}" ]; then
  cert_path="${CERT_DIR}/${TURN_CERT_FILE:?TURN_CERT_FILE is required when TURN_TLS_PORT is set}"
  pkey_path="${CERT_DIR}/${TURN_PKEY_FILE:?TURN_PKEY_FILE is required when TURN_TLS_PORT is set}"
  [ -r "$cert_path" ] || die "certificate not readable at $cert_path — check TURN_CERT_DIR/TURN_CERT_FILE and that TURN_CERT_GID can read it (see docker/README.md)"
  [ -r "$pkey_path" ] || die "private key not readable at $pkey_path — a Let's Encrypt privkey is usually root-only; see the TURN_CERT_GID note in docker/README.md"
  emit "tls-listening-port=${TURN_TLS_PORT}"
  emit "cert=${cert_path}"
  emit "pkey=${pkey_path}"
else
  emit "no-tls"
  emit "no-dtls"
fi

if [ "${TURN_NO_TCP_RELAY:-0}" = "1" ]; then emit "no-tcp-relay"; fi

# Anything else the operator wants, appended verbatim (one option per line).
if [ -n "${TURN_EXTRA_CONF:-}" ] && [ -r "$TURN_EXTRA_CONF" ]; then
  emit ""
  emit "# --- From TURN_EXTRA_CONF (${TURN_EXTRA_CONF}) ---"
  cat "$TURN_EXTRA_CONF" >> "$RENDERED_CONF"
fi

# Echo the effective config for the container log, minus the one line that
# must not be logged. Cheap, and it turns "why is the relay behaving like
# that" into a `docker compose logs` away.
echo "[coturn-entrypoint] effective config ($RENDERED_CONF):"
sed 's/^static-auth-secret=.*/static-auth-secret=<redacted>/' "$RENDERED_CONF" | sed 's/^/    /'

exec turnserver -c "$RENDERED_CONF" --log-file=stdout "$@"
